---
version: '3.8'

services:
  cryptpad:
    image: interhop/cryptpad:latest
    restart: unless-stopped
    hostname: cryptpad

    environment:
      - CPAD_MAIN_DOMAIN=${CPAD_MAIN_DOMAIN}
      - CPAD_SANDBOX_DOMAIN=${CPAD_SANDBOX_DOMAIN}
      - DATA_PATH=${DATA_PATH}
      - HTTP_PORT=${HTTP_PORT}
      - CPAD_TRUSTED_PROXY=${CPAD_TRUSTED_PROXY}
      - CPAD_HTTP2_DISABLE=true
      - CPAD_REALIP_RECURSIVE=on

    volumes:
      - ${DATA_PATH}/data/blob:/cryptpad/blob
      - ${DATA_PATH}/data/block:/cryptpad/block
      - ${DATA_PATH}/data/customize:/cryptpad/customize
      - ${DATA_PATH}/data/data:/cryptpad/data
      - ${DATA_PATH}/data/files:/cryptpad/datastore
      - ${DATA_PATH}/data/config.js:/cryptpad/config/config.js

    ports:
      - ${HTTP_PORT}:80

    expose:
      - ${HTTP_PORT}

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
